Feature chapter3
DoubleSentinel/EdJ-Edanaga-Unity pull request #10
Opened 2021-01-19 14:51 UTC by ThierryS72

2021-01-19 15:45 UTC, DoubleSentinel requested changes

2021-01-19 15:45 UTC, DoubleSentinel commented on Assets/Scripts/Chapters/ControllerChapter3.cs
> +    public bool EnableFlag { get; set; }
Pourquoi es-ce que ce flag est publique?

2021-01-19 15:45 UTC, DoubleSentinel commented on Assets/Scripts/Chapters/ControllerChapter3.cs
> +        conversationCallback = () => {
L'interêt d'un callback est de ne pas devoir différencier les cas avec des IF-ELSE mais de changer le callback quand on en a besoins.

2021-01-19 15:45 UTC, DoubleSentinel commented on Assets/Scripts/Chapters/ControllerChapter3.cs
> +    private void DisableEnableDnD()
Changer le nom de la méthode à ToggleDnD() et le code:

```c#
for (int i = 0; i < alternativesDnD.Length; i++)
{
    alternativesDnD[i].GetComponent<ObjectSettings>().LockObject = !EnableFlag;
}
if(EnableFlag)
    ShowPopup();

2021-01-19 15:45 UTC, DoubleSentinel commented on Assets/Scripts/Chapters/ControllerChapter3.cs
> +            return;
quel est l’intérêt de ces deux lignes de code?

2021-01-19 15:45 UTC, DoubleSentinel commented on Assets/Scripts/Chapters/ControllerChapter3.cs
> +    [SerializeField] private string PopupName = "Popup1";
non-object variable names should be camel-back cased (first letter uncapitalized)

2021-01-19 15:45 UTC, DoubleSentinel commented on Assets/Scripts/Chapters/ControllerChapter3.cs
> +   private void NextConv()
is this method ever called?

2021-01-19 15:45 UTC, DoubleSentinel commented on Assets/Scripts/Chapters/ControllerChapter3.cs
> +    //Return true if the 4 first elements of the two Array are the same
for both of these tests, does the order matter? if it doesn't, sort the lists before comparing

2021-01-19 15:45 UTC, DoubleSentinel commented on Assets/Scripts/Chapters/ControllerChapter3.cs
> +        //priorities2.gameObject.SetActive(false);
commented code

2021-01-19 15:45 UTC, DoubleSentinel commented on Assets/Scripts/Chapters/ControllerChapter3.cs
> +        go.SetActive(true);
I suggest doing this so as it adds a small fade animation on objects that have to be shown or hidden
```c#
private void ToggleGameObject(GameObject go, bool isShown)
{
    if (isShown)
    {
        go.SetActive(true);
        go.GetComponent<CanvasGroup>().DOFade(1f, 0.2f);
    }
    else
    {
        go.GetComponent<CanvasGroup>().DOFade( 0f, 0.2f).OnComplete(
            () =>
            {
                go.SetActive(false);
            });
    }
}
```

2021-01-19 15:45 UTC, DoubleSentinel commented on Assets/Scripts/Chapters/ControllerChapter3.cs
> +    private void HideGo(GameObject go)
With previous comment, remove this.

2021-01-19 15:45 UTC, DoubleSentinel commented on Assets/Scripts/Chapters/ControllerChapter3.cs
> +        go.SetActive(true);
Make sure your target game object has a CanvasGroup

2021-01-19 15:45 UTC, DoubleSentinel commented on Assets/Scripts/Chapters/ControllerChapter3.cs
> +    public void SetPreferedUser(int choice)
The whole system behind this method sounds a bit problematic; Why is the user preference a string? We never use this information? Do you use this string to test something? If so wouldn't it be better to use something else? Maybe an int since this method's input is an int?

2021-01-19 15:45 UTC, DoubleSentinel commented on Assets/Scripts/Utility/TestingEnvironment.cs
> +    //public List<string> AlternativesInformed { get; set; }
commented code

2021-01-19 15:45 UTC, DoubleSentinel commented on Assets/Scripts/Chapters/ControllerChapter3.cs
> +﻿using Doozy.Engine;
Throughout this entire file, the word "consistent" has been inconsistently misspelled. 😟

2021-01-19 15:45 UTC, DoubleSentinel commented on Assets/Scripts/Chapters/ControllerChapter2_1.cs
> +    private void ControlButtons(bool actionEnable)
First, what does "SceneBats" mean?
Second, what does "ControlButtons" mean? Do you mean something like "ToggleMapButtons"?
Third, what does "objectiveNumber" mean? Do you mean something like "userSelectedObjectiveNumber"?

```c#
for (int i = 0; i < sceneBats.Length; i++)
{
    if(i != objectiveNumber)
        sceneButtons[i].gameObject.GetComponent<UIButton>().Interactable = false;
    else
        sceneButtons[i].gameObject.GetComponent<UIButton>().Interactable = actionEnable;
}
```

2021-01-19 16:44 UTC, ThierryS72 commented on Assets/Scripts/Chapters/ControllerChapter3.cs
> +    public bool EnableFlag { get; set; }
C'était de façon à pouvoir l'atteindre depuis TestingEnvironment, je le met en private

2021-01-19 16:57 UTC, ThierryS72 commented on Assets/Scripts/Chapters/ControllerChapter3.cs
> +            return;
Si le prefab du popup est mal renseigné, alors aucune erreur est générée,  c'est vrai que sa n'a pas de sens dans ce cas préscis --> lignes effacées

2021-01-20 06:36 UTC, ThierryS72 commented on Assets/Scripts/Chapters/ControllerChapter3.cs
> +    private void DisableEnableDnD()
Merci Karim, j'ai changé la méthode

2021-01-20 06:53 UTC, ThierryS72 commented on Assets/Scripts/Chapters/ControllerChapter3.cs
> +    [SerializeField] private string PopupName = "Popup1";
Done!

2021-01-20 07:14 UTC, ThierryS72 commented on Assets/Scripts/Chapters/ControllerChapter3.cs
> +    //Return true if the 4 first elements of the two Array are the same
The order has to be the same, no modification needed.

2021-01-20 07:18 UTC, ThierryS72 commented on Assets/Scripts/Chapters/ControllerChapter3.cs
> +        //priorities2.gameObject.SetActive(false);
Erased!

2021-01-20 07:37 UTC, ThierryS72 commented on Assets/Scripts/Chapters/ControllerChapter3.cs
> +   private void NextConv()
Yes, it is called when the View-Loopback is loaded (from show view Doozy), it is my solution to allow 2 successive conversations .

2021-01-20 07:58 UTC, ThierryS72 commented on Assets/Scripts/Utility/TestingEnvironment.cs
> +    //public List<string> AlternativesInformed { get; set; }
Erased!

2021-01-20 08:02 UTC, ThierryS72 commented on Assets/Scripts/Chapters/ControllerChapter3.cs
> +﻿using Doozy.Engine;
Ok, could you please spell it?

2021-01-20 10:42 UTC, ThierryS72 commented on Assets/Scripts/Chapters/ControllerChapter3.cs
> +﻿using Doozy.Engine;
I found it in commentary, corrected!

2021-01-20 10:50 UTC, ThierryS72 commented on Assets/Scripts/Chapters/ControllerChapter3.cs
> +   private void NextConv()
This method has to be "public"

2021-01-20 12:10 UTC, ThierryS72 commented on Assets/Scripts/Chapters/ControllerChapter3.cs
> +    public void SetPreferedUser(int choice)
SetPrefredUser method used now Enum values

2021-01-20 15:00 UTC, ThierryS72 commented on Assets/Scripts/Chapters/ControllerChapter2_1.cs
> +    private void ControlButtons(bool actionEnable)
SceneBats is now renamed to SceneBuildings, objectiveNumber to userSelectedObjectiveNumber. I also renamed the method to AllowBuildingsSelection() and I added some commentaries.

2021-01-20 18:54 UTC, ThierryS72 commented on Assets/Scripts/Chapters/ControllerChapter3.cs
> +        conversationCallback = () => {
Ok, nouvelle méthode pour gérer les différents callbacks

2021-01-21 10:44 UTC, DoubleSentinel approved these changes
Good to go!

2021-01-21 10:45 UTC, merged